name: Python CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 pytest
    - name: Check code formatting with Black
      run: |
        black --check .
    - name: Check import formatting with isort
      run: |
        isort . --check-only
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Run unit tests with pytest
      run: |
        pytest
